apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-backend
  template:
    metadata:
      labels:
        app: inventario-backend
    spec:
      containers:
      - name: inventario-backend
        image: inventario-backend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: inventario-backend
spec:
  selector:
    app: inventario-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-frontend
  template:
    metadata:
      labels:
        app: inventario-frontend
    spec:
      containers:
      - name: inventario-frontend
        image: inventario-frontend:latest
        ports:
        - containerPort: 80
