apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly90YXRpYW5hZ2FyY2lhY29udHJlcmFzOkczblh5dWZrN0FHSEIxWjJAY2x1c3RlcjAudXpuc3A2Yy5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
